### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by raphydaphy** [RockBottomGame/RockBottom#19]
I made some adjustments to the lighting propogation and I personally think it looks a lot better, but since Ellpeck disagrees I thought I'd make an issue about it.

This is the new lighting
![Capture](https://user-images.githubusercontent.com/8121164/62834202-740d9000-bc8c-11e9-99e1-6bb2e50b3b25.PNG)

And this is what it looks like without my changes
![Capture2](https://user-images.githubusercontent.com/8121164/62834205-766fea00-bc8c-11e9-84a1-c7b9ddac68da.PNG)

What do you think? I've also been experimenting with an option that makes skylight come down but it has issues with chunk generation since it works bottom-up.

**Comment by Quarris** [comment]
I prefer the upper image. And as for the skylight, I dont think it is as big of a deal. It should be fine if the light doesnt go all the way down a 1000000 tile hole tbh

**Comment by Ellpeck** [comment]
yes

**Comment by Ellpeck** [comment]
this is a good feature please implement
